# Generated by Django 3.1.1 on 2020-09-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrow_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Arrows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_card_id', models.IntegerField(verbose_name='フロムカード')),
                ('to_card_id', models.IntegerField(verbose_name='トゥーカード')),
                ('label', models.CharField(max_length=255)),
                ('arrow_type_id', models.IntegerField(verbose_name='アロータイプ')),
                ('board_id', models.IntegerField(verbose_name='ボードID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('description', models.CharField(max_length=500, verbose_name='ディスクリプション')),
                ('thumbnail', models.CharField(max_length=255, verbose_name='サムネイル')),
                ('url_tail', models.CharField(max_length=255, verbose_name='テイル')),
                ('user_id', models.CharField(max_length=255, verbose_name='ユーザーID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Board_Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.IntegerField(verbose_name='ボードID')),
                ('tag_id', models.IntegerField(verbose_name='タグID')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=255, verbose_name='URL')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('summary', models.CharField(max_length=500, verbose_name='サマリー')),
                ('thumbnail', models.CharField(max_length=255, verbose_name='サムネイル')),
                ('positionX', models.IntegerField(verbose_name='x座標')),
                ('positionY', models.IntegerField(verbose_name='y座標')),
                ('board_id', models.IntegerField(verbose_name='ボードID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='ユーザーID')),
                ('board_id', models.IntegerField(verbose_name='ボードID')),
                ('content', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='ユーザーID')),
                ('board_id', models.IntegerField(verbose_name='ボードID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='タグ')),
            ],
        ),
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
