# Generated by Django 3.1.1 on 2020-10-05 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201005_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='comments1',
        ),
        migrations.RemoveField(
            model_name='board',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='board',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='card',
            name='arrows',
        ),
    ]
