# Generated by Django 3.1.1 on 2020-10-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201015_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='zoom',
            field=models.DecimalField(decimal_places=16, default=1, max_digits=17),
        ),
    ]
