# Generated by Django 3.1.1 on 2020-10-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_board_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='zoom',
            field=models.FloatField(default=1),
        ),
    ]
