# Generated by Django 3.1.1 on 2020-09-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200924_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='board_id',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='user',
        ),
    ]
