# Generated by Django 3.1.1 on 2020-10-03 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201003_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrow_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Arrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_card_id', models.IntegerField()),
                ('to_card_id', models.IntegerField()),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrow_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.arrow_type')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_arrows', to='api.board')),
            ],
        ),
    ]
