# Generated by Django 3.1.1 on 2020-09-27 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200925_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arrows',
            new_name='Arrow',
        ),
        migrations.RenameModel(
            old_name='Arrow_types',
            new_name='Arrow_type',
        ),
    ]
