# Generated by Django 3.1.1 on 2020-10-03 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_arrow_arrow_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='positionY',
            new_name='position_x',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='positionX',
            new_name='position_y',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='URL',
            new_name='url',
        ),
    ]
