# Generated by Django 3.1.1 on 2020-10-03 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201003_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrow',
            name='to_card_id',
        ),
        migrations.AddField(
            model_name='card',
            name='arrows',
            field=models.ManyToManyField(related_name='_card_arrows_+', through='api.Arrow', to='api.Card'),
        ),
        migrations.AlterField(
            model_name='arrow',
            name='from_card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.card'),
        ),
    ]
