# Generated by Django 3.1.1 on 2020-10-03 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201003_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrow',
            name='from_card_id',
        ),
        migrations.AddField(
            model_name='arrow',
            name='from_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='board_from_cards', to='api.card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arrow',
            name='to_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='board_to_cards', to='api.card'),
            preserve_default=False,
        ),
    ]
