# Generated by Django 3.1.1 on 2020-10-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200929_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='board',
            name='thumbnail',
        ),
    ]
