# Generated by Django 3.1.1 on 2020-10-03 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201003_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrow',
            old_name='arrow_type_id',
            new_name='arrow_type',
        ),
    ]
