# Generated by Django 3.1.1 on 2020-10-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201001_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrow',
            old_name='board_id',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='board_tag',
            old_name='board_id',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='board_tag',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='board_id',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='board_id',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='board',
            name='thumbnail',
            field=models.CharField(max_length=255, null=True, verbose_name='サムネイル'),
        ),
    ]
