# Generated by Django 3.1.1 on 2020-10-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201001_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='created',
            new_name='created_at',
        ),
    ]
