# Generated by Django 3.1.1 on 2020-10-04 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_auto_20201004_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='comments',
        ),
        migrations.AddField(
            model_name='board',
            name='comments1',
            field=models.ManyToManyField(related_name='comments2', through='api.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
