# Generated by Django 3.1.1 on 2020-10-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201004_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='comments1',
        ),
        migrations.RemoveField(
            model_name='board',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='board',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='card',
            name='arrows',
        ),
    ]
