# Generated by Django 3.1.1 on 2020-10-04 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_auto_20201004_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='comments1',
            field=models.ManyToManyField(related_name='comments2', through='api.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='likes',
            field=models.ManyToManyField(related_name='likes', through='api.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='tags',
            field=models.ManyToManyField(related_name='tags', through='api.Board_Tags', to='api.Tag'),
        ),
        migrations.AddField(
            model_name='card',
            name='arrows',
            field=models.ManyToManyField(related_name='_card_arrows_+', through='api.Arrow', to='api.Card'),
        ),
    ]
