# Generated by Django 3.1.1 on 2020-10-04 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201004_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='board',
            name='comments1',
        ),
        migrations.RemoveField(
            model_name='board',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='board',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='card',
            name='arrows',
        ),
        migrations.DeleteModel(
            name='Board_Tags',
        ),
        migrations.AddField(
            model_name='board_tag',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.board'),
        ),
        migrations.AddField(
            model_name='board_tag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag'),
        ),
    ]
