# Generated by Django 3.1.1 on 2020-10-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201001_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrow',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
