# Generated by Django 3.1.1 on 2020-10-04 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201004_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_tag',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_tags', to='api.board'),
        ),
        migrations.AlterField(
            model_name='board_tag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_boards', to='api.tag'),
        ),
    ]
